name: daily_pics
description: A new Flutter application.
version: 2.0.2+191010

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_ionicons:
    git: https://github.com/KagurazakaHanabi/flutter_ionicons.git
  cached_network_image: ^1.1.1
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.2.0
  flutter_staggered_grid_view: ^0.3.0
  http: ^0.12.0+2
  image_picker: ^0.6.1+4
  json_annotation: ^3.0.0
  package_info: ^0.4.0+6
  path_provider: ^1.3.0
  qr: ^1.2.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.3+4
  uni_links: ^0.2.0
  url_launcher: ^5.1.4

builders:
  json_serializable: ^3.2.2

flutter:
  uses-material-design: false
  assets:
    - res/
    - res/avatars/
